experiment_name: "bo_test"
seed: 42
device: "cpu"

search_space:
  bounds:
    x1: [ 0.0, 1.0 ]
    x2: [ -2.0, 2.0 ]
  variable_types:
    x1: "continuous"
    x2: "continuous"

objective:
  objective_name: "branin"
  minimize: true
  noise_type: "gaussian"
  noise_std: 0.01
  evaluation_budget: 50

model:
  gp_type: "SingleTaskGP"
  mean_module: "constant"
  covar_module:
    type: "Matern"
    nu: 2.5
  input_transform: "normalize"
  outcome_transform: "standardize"

acquisition:
  acq_function: "EI"
  acq_params:
    xi: 0.01

acq_optimizer:
  optimizer: "LBFGS"
  num_restarts: 10
  raw_samples: 256

execution:
  num_init_points: 5
  num_iterations: 30
  checkpoint_file: "bo_checkpoint.json"
  log_interval: 5
  save_results: "results.json"